import os
import sys
import logging
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

ARCHITECTURE_FILE = "ARCHITECTURE.md"


class Architecture:
    """
    Scans the kernel component tree and regenerates the architecture document.
    A 'component'    is any directory under dev/kernel/ that contains both 'inc/' and 'code/' subdirs.
    A 'subcomponent' is any directory directly under <component>/code/ (ignoring files).
    """

    def __init__(self, verbosity: bool):
        self._verbosity          = verbosity
        self._KERNEL_ROOT_DIR    = os.path.join(os.getcwd(), "dev", "kernel")
        self._OUTPUT_FILE        = os.path.join(os.getcwd(), ARCHITECTURE_FILE)


    # --------------------------------------------------------------------------
    # Scanning
    # --------------------------------------------------------------------------

    def _is_component(self, path: str) -> bool:
        """A valid component directory has both 'inc/' and 'code/' children."""
        return (
            os.path.isdir(os.path.join(path, "inc"))  and
            os.path.isdir(os.path.join(path, "code"))
        )


    def _get_subcomponents(self, component_path: str) -> list:
        """Return sorted list of subcomponent names found under <component>/code/."""
        code_dir = os.path.join(component_path, "code")
        subcomponents = []
        for entry in sorted(os.listdir(code_dir)):
            entry_path = os.path.join(code_dir, entry)
            if os.path.isdir(entry_path):
                subcomponents.append(entry)
        return subcomponents


    def scan(self) -> dict:
        """
        Walk dev/kernel/ and return:
            { component_name: [subcomponent_name, ...], ... }
        Sorted alphabetically.
        """
        arch = {}

        if not os.path.isdir(self._KERNEL_ROOT_DIR):
            logging.warning(f"Kernel root not found: {self._KERNEL_ROOT_DIR}")
            return arch

        for entry in sorted(os.listdir(self._KERNEL_ROOT_DIR)):
            entry_path = os.path.join(self._KERNEL_ROOT_DIR, entry)
            if os.path.isdir(entry_path) and self._is_component(entry_path):
                arch[entry] = self._get_subcomponents(entry_path)
                if self._verbosity:
                    logging.info(f"Found component: {entry}  subcomponents: {arch[entry]}")

        return arch


    # --------------------------------------------------------------------------
    # Rendering
    # --------------------------------------------------------------------------

    def _render_tree(self, arch: dict) -> str:
        lines = ["```", "kernel/"]
        for component, subcomponents in arch.items():
            lines.append(f"├── {component}/")
            lines.append(f"│   ├── inc/")
            lines.append(f"│   │   ├── krn/")
            lines.append(f"│   │   └── usr/")
            lines.append(f"│   └── code/")
            for i, sub in enumerate(subcomponents):
                prefix = "└──" if i == len(subcomponents) - 1 else "├──"
                lines.append(f"│       {prefix} {sub}/")
        lines.append("```")
        return "\n".join(lines)


    def _render_markdown(self, arch: dict) -> str:
        ts      = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        n_comp  = len(arch)
        n_sub   = sum(len(v) for v in arch.values())

        sections = []

        # Header
        sections.append(
            f"# LeonardOS — Architecture\n\n"
            f"> Auto-generated by `tools/scripts/Architecture.py` — {ts}  \n"
            f"> **{n_comp}** component(s) · **{n_sub}** subcomponent(s)\n"
        )

        # Directory tree
        sections.append("\n## Directory tree\n")
        sections.append(self._render_tree(arch))

        # Detail table per component
        sections.append("\n## Component details\n")
        if not arch:
            sections.append("_No components found._\n")
        else:
            for component, subcomponents in arch.items():
                sections.append(f"### `{component}`\n")
                if subcomponents:
                    sections.append("| Subcomponent | Public headers | Sources |")
                    sections.append("|---|---|---|")
                    for sub in subcomponents:
                        sections.append(
                            f"| `{sub}` "
                            f"| `{component}/code/{sub}/inc/` "
                            f"| `{component}/code/{sub}/src/` |"
                        )
                else:
                    sections.append("_No subcomponents yet._")
                sections.append("")

        return "\n".join(sections)


    # --------------------------------------------------------------------------
    # Public entry points
    # --------------------------------------------------------------------------

    def generate(self) -> None:
        """Scan the tree and write ARCHITECTURE.md at the project root."""
        arch     = self.scan()
        content  = self._render_markdown(arch)

        with open(self._OUTPUT_FILE, "w") as f:
            f.write(content)

        logging.info(f"Architecture written to {self._OUTPUT_FILE}")


    def print_summary(self) -> None:
        """Print a compact component/subcomponent summary to stdout."""
        arch = self.scan()
        print(f"\n{'─' * 48}")
        print(f"  LeonardOS architecture  ({len(arch)} components)")
        print(f"{'─' * 48}")
        for component, subcomponents in arch.items():
            print(f"  [{component}]")
            for sub in subcomponents:
                print(f"      └─ {sub}")
        print(f"{'─' * 48}\n")


if __name__ == "__main__":
    verbosity    = True if len(sys.argv) > 1 and sys.argv[1] != "0" else False
    architecture = Architecture(verbosity)
    architecture.generate()
    architecture.print_summary()
