# ==============================================================================
# Set the library name
# ==============================================================================
set(LIB_PATH ${LIB_PATH})
set(LIB_NAME ${LIB_NAME})

# ==============================================================================
# Create library
# ==============================================================================
add_library(${LIB_NAME}
    INTERFACE
)

# ==============================================================================
# Add include directories for the library
# ==============================================================================
target_include_directories(${LIB_NAME}
    INTERFACE
        ${LIB_PATH}/inc/usr     # Public headers for user interface
)
